ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "weeklyDigestSentAt" TIMESTAMP(3);
ALTER TABLE "Show" ADD COLUMN IF NOT EXISTS "capacityAlertSentAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "earningsSummarySentAt" TIMESTAMP(3);
